// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnEogD1_3Fur30yvaMcTwrS8758XqcKBs',
    appId: '1:511272600016:web:bdd55593305e500cce79d5',
    messagingSenderId: '511272600016',
    projectId: 'one-tech-id',
    authDomain: 'one-tech-id.firebaseapp.com',
    storageBucket: 'one-tech-id.appspot.com',
    measurementId: 'G-4L9KZ0WZH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQet290y-cEd7hhol2eWc6E6wSbJ8EZrk',
    appId: '1:511272600016:android:06a4a75df120064cce79d5',
    messagingSenderId: '511272600016',
    projectId: 'one-tech-id',
    storageBucket: 'one-tech-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5JMCXN6xZ4RNRZxDxMvFnsq2mZp3cQDw',
    appId: '1:511272600016:ios:ae8a125100046616ce79d5',
    messagingSenderId: '511272600016',
    projectId: 'one-tech-id',
    storageBucket: 'one-tech-id.appspot.com',
    iosBundleId: 'com.example.oneTechDataControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5JMCXN6xZ4RNRZxDxMvFnsq2mZp3cQDw',
    appId: '1:511272600016:ios:ad82169f21dab2cece79d5',
    messagingSenderId: '511272600016',
    projectId: 'one-tech-id',
    storageBucket: 'one-tech-id.appspot.com',
    iosBundleId: 'com.example.oneTechIdFrontend.RunnerTests',
  );
}
